# -*- coding: utf-8 -*-
"""CS EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19s26_9URYjJjhbD06MiYD9vqyLyk2CYt
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv('train.csv')
df.head()

df.info()

# Show duplicate rows
df[df.duplicated()]

#drop unnecessary columns
df = df.drop(['ID','Customer_ID','Month','Name','SSN', 'Type_of_Loan', 'Changed_Credit_Limit', 'Monthly_Inhand_Salary'], axis = 1)

target_mapping = {'Poor': 0, 'Standard': 1, 'Good': 1}

# Map the target variable
df['Credit_Score'] = df['Credit_Score'].map(target_mapping)

df = df.replace("_", "", regex=True)

df[df.eq('').any(axis=1)]

rows_with_empty_values = df[df.eq('').any(axis=1)]

# Fill empty values with np.nan in selected rows
df.loc[rows_with_empty_values.index] = df.loc[rows_with_empty_values.index].replace('', np.nan)

df.shape

df.isnull().sum()

df.describe()

df.describe(include='object').T

#check not unique values
df.Age.nunique()

df.Age.value_counts(ascending=False).head(10)

import re

def non_numeric_values(df, column_name):
    # Define a regular expression pattern to match numeric characters
    pattern = r'\D+'

    # Find non-numeric values using regular expression
    non_numeric_values = df[column_name].astype(str).str.findall(pattern)

    # Flatten the list of lists
    non_numeric_values = [item for sublist in non_numeric_values for item in sublist]

    unique_non_numeric_values = set(non_numeric_values)

    return unique_non_numeric_values

unique_non_numeric = non_numeric_values(df, 'Age')
print(unique_non_numeric)

df['Age'] = pd.to_numeric(df['Age'], errors='coerce') #Converts the 'Age' column to numeric values (integers or floats).
df[df['Age'] < 0]['Age'].unique() #Filters the df to only show rows where Age <df.Occupation.value_counts() 0.

df[df['Age'] > 100]['Age'].unique()

#drop age > 100 & < 0
df.drop(df[df['Age'] > 100].index, inplace = True)
df.drop(df[df['Age'] < 0].index, inplace = True)

"""Occupation"""

df.Occupation.value_counts()

df.Occupation.isnull().sum() #check nulls

df.loc[pd.isna(df['Occupation']), 'Occupation'] = 'Other'

"""Num_Bank_Accounts"""

non_numeric_values(df, 'Num_Bank_Accounts')

df[df.Num_Bank_Accounts < 0]['Num_Bank_Accounts'].count()

df.drop(df[df['Num_Bank_Accounts'] < 0].index, inplace=True)

"""Num_of_Loan"""

non_numeric_values(df, 'Num_of_Loan')

df['Num_of_Loan'] = pd.to_numeric(df['Num_of_Loan'], errors='coerce')
df[df['Num_of_Loan'] < 0]['Num_of_Loan'].unique()

df['Num_of_Loan'].unique()

df[df['Num_of_Loan'] < 0 ]['Num_of_Loan'].count()

df.drop(df[df['Num_of_Loan'] < 0].index, inplace = True)

df.shape

"""Delay_from_due_date"""

non_numeric_values(df, 'Delay_from_due_date')

df[df['Delay_from_due_date'] < 0]['Delay_from_due_date'].unique()

df['Delay_from_due_date'].nunique()

df[df['Delay_from_due_date'] < 0 ]['Delay_from_due_date'].count()

df.drop(df[df['Delay_from_due_date'] < 0].index, inplace=True)
df.shape

"""Num_of_Delayed_Payment"""

non_numeric_values(df, 'Num_of_Delayed_Payment')

df['Num_of_Delayed_Payment'] = pd.to_numeric(df['Num_of_Delayed_Payment'], errors='coerce')
df[df['Num_of_Delayed_Payment'] < 0]['Num_of_Delayed_Payment'].unique()

df[df['Num_of_Delayed_Payment'] < 0]['Num_of_Delayed_Payment'].count()

df.drop(df[df['Num_of_Delayed_Payment'] < 0].index, inplace=True)
df.shape

df['Num_of_Delayed_Payment'].value_counts().head(10)

df['Num_of_Delayed_Payment'].isnull().sum()

"""KNN impute"""

from sklearn.impute import KNNImputer
def knn_impute_column(df, column_name, n_neighbors=5):
  column_to_impute = df[[column_name]]
  imputer = KNNImputer(n_neighbors=n_neighbors)
  column_imputed = imputer.fit_transform(column_to_impute)
  df[column_name] = column_imputed

  return df

df = knn_impute_column (df, 'Num_of_Delayed_Payment')

df['Num_of_Delayed_Payment'].isnull().sum()

"""Num_Credit_Inquiries"""

non_numeric_values(df, 'Num_Credit_Inquiries')

df[df['Num_Credit_Inquiries'] < 0]['Num_Credit_Inquiries'].unique()

df['Num_Credit_Inquiries'].isnull().sum()

df['Num_Credit_Inquiries'].nunique()

df['Num_Credit_Inquiries'].value_counts().head(10)

df = knn_impute_column(df, 'Num_Credit_Inquiries')
df['Num_Credit_Inquiries'].isnull().sum()

"""Credit Mix"""

df.Credit_Mix.value_counts()

df.Credit_Mix.isnull().sum()

df['Credit_Mix'].fillna('Unknown', inplace=True)

df['Credit_Mix'].astype('object')

df.Credit_Mix.value_counts()

"""Credit_History_Age"""

df.Credit_History_Age.value_counts()

df.Credit_History_Age.isnull().sum()

df.Credit_History_Age.value_counts()

# Group by 'Credit_Mix' and calculate mode for 'Credit_History_Age' within each group
mode_by_credit_mix = df.groupby('Credit_Mix')['Credit_History_Age'].transform(lambda x: x.mode()[0])

df['Credit_History_Age'].fillna(mode_by_credit_mix, inplace=True)

df.Credit_History_Age.isnull().sum()

df.Credit_History_Age.value_counts()

# Extract years and months from 'Credit_History_Age' column
df['Credit_History_Years'] = df['Credit_History_Age'].str.extract(r'(\d+) Years').astype(int)
df['Credit_History_Months'] = df['Credit_History_Age'].str.extract(r'(\d+) Months').astype(int)

df.drop(columns=['Credit_History_Age'], inplace=True)

df.head()

# Convert years to months and add with months to get total months
df['Credit_History_Age_Months'] = df['Credit_History_Years'] * 12 + df['Credit_History_Months']

# Drop the 'Credit_History_Years' and 'Credit_History_Months' columns
df.drop(columns=['Credit_History_Years', 'Credit_History_Months'], inplace=True)

df.head()

"""Payment of Min Amount"""

df.Payment_of_Min_Amount.value_counts()

df.Amount_invested_monthly.nunique()

non_numeric_values(df, 'Amount_invested_monthly')

df['Amount_invested_monthly'] = pd.to_numeric(df['Amount_invested_monthly'], errors='coerce')
df[df['Amount_invested_monthly'] < 0]['Amount_invested_monthly'].unique()

df.Amount_invested_monthly.value_counts().head(15)

df[df.Amount_invested_monthly.isna()].sample(10)

df = knn_impute_column(df, 'Amount_invested_monthly')

df.Amount_invested_monthly.isnull().sum()

df.Amount_invested_monthly.value_counts().head(10)

df[df['Amount_invested_monthly'] == 10000]['Amount_invested_monthly'].count()

"""Payment Behavior"""

df.Payment_Behaviour.value_counts()

#replace !@9#%8 with NaN
df['Payment_Behaviour'].replace('!@9#%8' , pd.NA, inplace=True)

#fill missing value with mode
mode_value = df['Payment_Behaviour'].mode()[0]
df['Payment_Behaviour'].fillna(mode_value, inplace=True)

df.Payment_Behaviour.value_counts()

"""Monthly Balance"""

df.Monthly_Balance.isnull().sum()

non_numeric_values(df, 'Monthly_Balance')

df['Monthly_Balance'] = pd.to_numeric(df['Monthly_Balance'], errors='coerce')
df[df['Monthly_Balance'] < 0]['Monthly_Balance'].count()

df.drop(df[df['Monthly_Balance'] < 0].index, inplace = True)

df['Monthly_Balance'].value_counts().head(15)

df['Monthly_Balance'].max()

df['Monthly_Balance'].min()

df['Monthly_Balance'].mean()

df = knn_impute_column(df, 'Monthly_Balance')
df.Monthly_Balance.isnull().sum()

#change data types
df['Annual_Income'] = df['Annual_Income'].astype(float)
df['Outstanding_Debt'] = df['Outstanding_Debt'].astype(float)

df.info()

df.head()

"""Feature Engineering"""

df['Debt_to_Income'] = df['Outstanding_Debt'] / (df['Annual_Income'] + 1e-5)
df['Investment_to_Income'] = df['Amount_invested_monthly'] * 12 / (df['Annual_Income'] + 1e-5)
df['Loan_Account_Ratio'] = df['Num_of_Loan'] / (df['Num_Bank_Accounts'] + 1)
df['Account_Activity_Index'] = df['Num_of_Loan'] + df['Num_Credit_Card'] + df['Num_Bank_Accounts']

df.head()

df.tail()

df[df['Num_Credit_Card'] > 20]

import matplotlib.pyplot as plt
import seaborn as sns

# Select only numerical columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Compute correlation matrix
corr_matrix = df[numeric_cols].corr()

# Plot full heatmap
plt.figure(figsize=(16, 12))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5)
plt.title("Correlation Heatmap of All Numerical Features", fontsize=16)
plt.show()

df = df[df['Interest_Rate'] <= 50]

# Cap Loan Count
df = df[df['Num_of_Loan'] <= 15]

# Round and cap Delayed Payments
df['Num_of_Delayed_Payment'] = df['Num_of_Delayed_Payment'].round().astype('Int64')
df = df[df['Num_of_Delayed_Payment'] <= 15]

# Round and cap Credit Inquiries
df['Num_Credit_Inquiries'] = df['Num_Credit_Inquiries'].round().astype('Int64')
df = df[df['Num_Credit_Inquiries'] <= 10]

# Cap Number of Credit Cards
df = df[df['Num_Credit_Card'] <= 10]

# (Optional) Reset index after row removal
df.reset_index(drop=True, inplace=True)

df.to_csv('CS_Cleaned1.csv', index = False)